export const fallbackTeams = [
  { id: 1,  name: "URIEL Y LEO",                score: 0, flag:"mx", logo:"kidstronic.png",   category: "SUMO_ES" },
  { id: 2,  name: "TERRENEITOR",                score: 0, flag:"mx", logo:"kidstronic.png",   category: "SUMO_ES" },
  { id: 3,  name: "CYBERSALLE - CODERS",        score: 0, flag:"co", logo:"cybersalle.png",   category: "A-MAZE-ING_ES" },
  { id: 4,  name: "CockroachBots",              score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO1K_HS" },
  { id: 5,  name: "JaamBots",                   score: 0, flag:"mx", logo:"jaambots.png",     category: "SUMO1K_HS" },
  { id: 6,  name: "ValleBot_1",                 score: 0, flag:"mx", logo:"vallebot.png",     category: "SOCCER_HS" },
  { id: 7,  name: "ValleBot_2",                 score: 0, flag:"mx", logo:"vallebot.png",     category: "SOCCER_MS" },
  { id: 8,  name: "ValleBot_4",                 score: 0, flag:"mx", logo:"vallebot.png",     category: "A-MAZE-ING_MS" },
  { id: 9,  name: "ValleBot_3",                 score: 0, flag:"mx", logo:"vallebot.png",     category: "A-MAZE-ING_ES" },
  { id: 10, name: "Iron Bots",                  score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO1K_HS" },
  { id: 11, name: "Mechanic Fight",             score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO1K_HS" },
  { id: 12, name: "Short Circuit",              score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO1K_HS" },
  { id: 13, name: "Conalep Piedras Negras",     score: 0, flag:"mx", logo:"conaleppn.png",    category: "SUMO1K_HS" },
  { id: 14, name: "Innademy - Elian",           score: 0, flag:"mx", logo:"innademy.png",     category: "SUMO_ES" },
  { id: 15, name: "Innademy - Santino",         score: 0, flag:"mx", logo:"innademy.png",     category: "A-MAZE-ING_ES" },
  { id: 16, name: "Innademy - Annia",           score: 0, flag:"mx", logo:"innademy.png",     category: "A-MAZE-ING_ES" },
  { id: 17, name: "FireFighters Paxtle",        score: 0, flag:"mx", logo:"paxtle.png",       category: "FIRE_HS" },
  { id: 18, name: "BERSERK",                    score: 0, flag:"mx", logo:"conalepvs.png",    category: "SUMO3K_HS" },
  { id: 19, name: "GOWAN",                      score: 0, flag:"mx", logo:"conalepvs.png",    category: "SUMO1K_HS" },
  { id: 20, name: "LA GOTA GORDA",              score: 0, flag:"mx", logo:"kidstronic.png",   category: "SUMO_MS" },
  { id: 21, name: "LOS JASSITOS",               score: 0, flag:"mx", logo:"kidstronic.png",   category: "SUMO_MS" },
  { id: 22, name: "DUST VADER",                 score: 0, flag:"mx", logo:"kidstronic.png",   category: "SUMO_MS" },
  { id: 23, name: "EL PAPUMOVIL",               score: 0, flag:"mx", logo:"kidstronic.png",   category: "SUMO_ES" },
  { id: 24, name: "SAMABOT",                    score: 0, flag:"mx", logo:"kidstronic.png",   category: "SUMO_ES" },
  { id: 25, name: "Dangerous Robot",            score: 0, flag:"mx", logo:"logomx.png",       category: "SOCCER_MS" },
  { id: 26, name: "Steel Dragons",              score: 0, flag:"mx", logo:"logomx.png",       category: "SOCCER_MS" },
  { id: 27, name: "Jamaicatron",                score: 0, flag:"mx", logo:"jamaicatron.png",  category: "LINE_HS" },
  { id: 28, name: "Garrita puma",               score: 0, flag:"mx", logo:"logomx.png",       category: "FAST_UP" },
  { id: 29, name: "Electropumas",               score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO3K_HS" },
  { id: 30, name: "Azulito FS",                 score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO3K_HS" },
  { id: 31, name: "Rojito FS",                  score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO3K_HS" },
  { id: 32, name: "Mictlān",                    score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO1K_HS" },
  { id: 33, name: "Brainbots ICPD_ES",          score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO_ES" },
  { id: 34, name: "Brainbots ICPD_MS",          score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO_MS" },
  { id: 35, name: "Conalep Frontera - ¡K-BOOM!",score: 0, flag:"mx", logo:"kboom.png",        category: "SUMO3K_HS" },
  { id: 36, name: "Conalep Frontera - ¡K-BOOM!",score: 0, flag:"mx", logo:"kboom.png",        category: "SUMO1K_HS" },
  { id: 37, name: "Firebots",                   score: 0, flag:"mx", logo:"logomx.png",       category: "FIRE_HS" },
  { id: 38, name: "WABYS",                      score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO1K_HS" },
  { id: 39, name: "AmericanoColombia",          score: 0, flag:"co", logo:"logoco.png",       category: "SOCCER_HS" },
  { id: 40, name: "ColamerCo",                  score: 0, flag:"co", logo:"logoco.png",       category: "SOCCER_HS" },
  { id: 41, name: "S6power",                    score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO_MS" },
  { id: 42, name: "Cidemgladiadores",           score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO_MS" },
  { id: 43, name: "Hidrobots",                  score: 0, flag:"mx", logo:"logomx.png",       category: "FAST_MS" },
  { id: 44, name: "Tecnosec6",                  score: 0, flag:"mx", logo:"logomx.png",       category: "FAST_MS" },
  { id: 45, name: "Robocidem",                  score: 0, flag:"mx", logo:"logomx.png",       category: "FAST_MS" },
  { id: 46, name: "MecaRaptors",                score: 0, flag:"mx", logo:"logomx.png",       category: "FAST_UP" },
  { id: 47, name: "MecaRaptors",                score: 0, flag:"mx", logo:"logomx.png",       category: "FAST_MS" },
  { id: 48, name: "Anonimus Robots",            score: 0, flag:"mx", logo:"logomx.png",       category: "SOCCER_MS" },
  { id: 49, name: "MANTARRAYA",                 score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO3K_HS" },
  { id: 50, name: "Conalep Reynosa",            score: 0, flag:"mx", logo:"logomx.png",       category: "SUMO1K_HS" },
  { id: 51, name: "GalacticosNP",               score: 0, flag:"mx", logo:"logomx.png",       category: "SOCCER_HS" },
  { id: 52, name: "RB200",                      score: 0, flag:"mx", logo:"conaleprb.png",    category: "SUMO3K_HS" },
  { id: 53, name: "Q Kids LF Fogonazo HS",      score: 0, flag:"mx", logo:"qkids.png",        category: "LINE_HS" },
  { id: 54, name: "Q Kids Sumo Lego Moto Moto MS",score: 0, flag:"mx", logo:"qkids.png",      category: "SUMO_MS" },
  { id: 55, name: "Q Kids Soccer HS",           score: 0, flag:"mx", logo:"qkids.png",        category: "SOCCER_HS" },
  { id: 56, name: "Q Kids Soccer ES 02",        score: 0, flag:"mx", logo:"qkids.png",        category: "SOCCER_MS" },
  { id: 57, name: "Q Kids Soccer ES 01",        score: 0, flag:"mx", logo:"qkids.png",        category: "SOCCER_MS" },
  { id: 58, name: "Q Kids AMZ MS",              score: 0, flag:"mx", logo:"qkids.png",        category: "A-MAZE-ING_MS" },
  { id: 59, name: "Q Kids AMZ ES 02",           score: 0, flag:"mx", logo:"qkids.png",        category: "A-MAZE-ING_ES" },
  { id: 60, name: "Q Kids AMZ ES 01",           score: 0, flag:"mx", logo:"qkids.png",        category: "A-MAZE-ING_ES" },
  { id: 61, name: "Colegio Nuevo San Luis Gonzaga",score: 0, flag:"co", logo:"logoco.png",    category: "A-MAZE-ING_ES" },
  { id: 62, name: "Metatroniks",                score: 0, flag:"mx", logo:"metatroniks.png",  category: "ENTRE_HS" },
  { id: 63, name: "Wildcats",                   score: 0, flag:"mx", logo:"katatronik.png",   category: "ENTRE_HS" },
  { id: 64, name: "Thundercats",                score: 0, flag:"mx", logo:"katatronik.png",   category: "FIRE_HS" },
  { id: 65, name: "Lynx",                       score: 0, flag:"mx", logo:"katatronik.png",   category: "FIRE_HS" },
  { id: 66, name: "Crazy Cats",                 score: 0, flag:"mx", logo:"katatronik.png",   category: "SUMO_MS" },
  { id: 67, name: "Magic Cats",                 score: 0, flag:"mx", logo:"katatronik.png",   category: "A-MAZE-ING_ES" },
  { id: 68, name: "Cheetahs",                   score: 0, flag:"mx", logo:"katatronik.png",   category: "A-MAZE-ING_ES" },
  { id: 69, name: "Lions",                      score: 0, flag:"mx", logo:"katatronik.png",   category: "A-MAZE-ING_MS" },
  { id: 70, name: "Tigers",                     score: 0, flag:"mx", logo:"katatronik.png",   category: "A-MAZE-ING_ES" },
  { id: 71, name: "Code Bots - Aspaen Neiva",   score: 0, flag:"mx", logo:"aspaen.png",       category: "A-MAZE-ING_MS" },

];
